<a href="https://colab.research.google.com/github/tucosh/kaggle/blob/main/tensorflow_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# from https://www.tensorflow.org/tutorials/quickstart/beginner

import tensorflow as tf
print('TensorFlow version: ', tf.__version__)

TensorFlow version:  2.17.1


In [8]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train.shape

(60000, 28, 28)

In [9]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5790833 ,  0.41483063,  0.41868883,  0.00812634, -0.2428297 ,
        -0.5338856 ,  0.50472313,  0.6390595 ,  0.5047244 ,  0.3805145 ]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

3.1634812

In [15]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8615 - loss: 0.4807
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9548 - loss: 0.1474
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9679 - loss: 0.1049
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9737 - loss: 0.0874
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9764 - loss: 0.0740


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9757 - loss: 0.0745


[0.07446054369211197, 0.9757000207901001]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.8265909e-07, 1.9969319e-08, 4.8594152e-06, 1.7296270e-04,
        1.3983426e-10, 6.3702458e-07, 3.7883321e-12, 9.9978632e-01,
        2.4994667e-06, 3.1785978e-05],
       [8.0556534e-10, 2.1272567e-04, 9.9978560e-01, 1.5790620e-06,
        7.7757116e-16, 7.5617216e-08, 6.2781785e-10, 2.5476679e-14,
        3.2965289e-08, 4.9489742e-13],
       [5.9861634e-07, 9.9888557e-01, 9.3726150e-05, 1.0874845e-05,
        1.5358640e-04, 3.6294416e-05, 6.6546686e-06, 6.9779082e-04,
        1.1398582e-04, 9.3164618e-07],
       [9.9950993e-01, 1.9381691e-10, 1.1602918e-05, 6.1045490e-08,
        1.6552725e-07, 3.4903653e-06, 4.7229062e-04, 2.8010311e-07,
        8.6080822e-09, 2.2835868e-06],
       [2.7051833e-06, 4.3966317e-10, 7.4468107e-06, 7.9348377e-09,
        9.9910897e-01, 5.4954231e-08, 4.4795361e-06, 6.7291636e-05,
        3.8193193e-07, 8.0853258e-04]], dtype=float32)>